[build]
target = [
  "x86_64-linux-android"
  "aarch64-linux-android"
  "x86_64-apple-ios"
  "aarch64-apple-ios"
  "x86_64-unknown-linux-gnu"
  "aarch64-unknown-linux-gnu"
  "x86_64-pc-windows-msvc"
  "aarch64-pc-windows-msvc"
  "x86_64-apple-darwin"
  "aarch64-apple-darwin"
]
